DROP TABLE IF EXISTS SYS_USER;

CREATE TABLE SYS_USER
(
    ID          BIGINT  NOT NULL COMMENT '主键ID',
    USERNAME    VARCHAR NULL DEFAULT NULL COMMENT '用户名',
    NICKNAME    VARCHAR NULL DEFAULT NULL COMMENT '昵称',
    PASSWORD    VARCHAR NULL DEFAULT NULL COMMENT '密码',
    CREATE_TIME TIMESTAMP COMMENT '创建日期',
    UPDATE_TIME TIMESTAMP COMMENT '更新日期',
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS SYS_ROLE;
CREATE TABLE SYS_ROLE
(
    ID          BIGINT AUTO_INCREMENT COMMENT '主键ID',
    NAME        VARCHAR NULL DEFAULT NULL COMMENT '角色名',
    CREATE_TIME TIMESTAMP COMMENT '创建日期',
    UPDATE_TIME TIMESTAMP COMMENT '更新日期',
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS SYS_PERMISSION;
CREATE TABLE SYS_PERMISSION
(
    ID          BIGINT AUTO_INCREMENT COMMENT '主键ID',
    NAME        VARCHAR NOT NULL COMMENT '权限名',
    DESCRIPTION VARCHAR NOT NULL COMMENT '权限名',
    CREATE_TIME TIMESTAMP COMMENT '创建日期',
    UPDATE_TIME TIMESTAMP COMMENT '更新日期',
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS SYS_ROLE_PERMISSION;
CREATE TABLE SYS_ROLE_PERMISSION
(
    ID            BIGINT AUTO_INCREMENT COMMENT '主键ID',
    ROLE_ID       BIGINT NOT NULL COMMENT '角色ID',
    PERMISSION_ID BIGINT NOT NULL COMMENT '菜单ID',
    CREATE_TIME   TIMESTAMP COMMENT '创建日期',
    UPDATE_TIME   TIMESTAMP COMMENT '更新日期',
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS SYS_USER_ROLE;
CREATE TABLE SYS_USER_ROLE
(
    ID          BIGINT AUTO_INCREMENT COMMENT '主键ID',
    ROLE_ID     BIGINT NOT NULL COMMENT '角色ID',
    USER_ID     BIGINT NOT NULL COMMENT '用户ID',
    CREATE_TIME TIMESTAMP COMMENT '创建日期',
    UPDATE_TIME TIMESTAMP COMMENT '更新日期',
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS BIZ_BOOK;
CREATE TABLE BIZ_BOOK
(
    ID          BIGINT AUTO_INCREMENT COMMENT '主键ID',
    NAME        VARCHAR         NOT NULL COMMENT '书名',
    AUTHOR      VARCHAR         NOT NULL COMMENT '作者',
    PRICE       DECIMAL(28, 10) NOT NULL COMMENT '单价',
    CODE        VARCHAR         NOT NULL COMMENT '条形码',
    DESCRIPTION VARCHAR         NOT NULL COMMENT '描述',
    CREATE_TIME TIMESTAMP COMMENT '创建日期',
    UPDATE_TIME TIMESTAMP COMMENT '更新日期',
    PRIMARY KEY (ID)
);

